### ISSUE TITLE
Allow custom property mapping

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticTasks#10]
### Setup and configuration

- MediaWiki | 1.32.1 (c6f078c)05:11, 11. Mai 2019
- PHP | 7.2.17-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.2
- Semantic MediaWiki | 3.1.0-alpha (81df573) 14:51, 13. Mai 2019
- SemanticTasks | 2.0.0-alpha (7f4b7e3) 09:47, 16. Mai 2019

### Issue
If I understand correctly the properties "Assigned to", "Carbon copy", "Reminder at" and "Target date" are hard coded, i.e. cannot be changed. I believe it will be a very good improvement if this could be either configured or changed via dedicated system messages.

**Comment by PeterTheOne** [comment]
What do you specifically mean with "dedicated system messages"? Is #11 correct?

**Comment by kghbln** [comment]
#11 is about adding configuration parameters to define the properties used for the notifications. A dedicated system message would be page "MediaWiki:ST-Assigned-to" or alike holding the name of the property to be used, in this case "Assigned to" I believe the Semantic Glossary extension is using the system message approach. However doing it with a configuration parameter is probably easier.

**Comment by PeterTheOne** [comment]
this is done in #11
