### ISSUE TITLE
Maintenance script include error

### ISSUE THREAD

**Issue by YOUR1** [SemanticMediaWiki/SemanticTasks#14]
https://github.com/SemanticMediaWiki/SemanticTasks/blob/76216872a8a8be6edad64e2c6b7623e51ae51016/maintenance/checkForReminders.php#L11

The referenced file does not exist?

**Comment by kghbln** [comment]
Thanks for reporting. Indeed the file was moved and renamed with #7  to "SemanticTasksMailer.php".

@PeterTheOne FYI

**Comment by YOUR1** [comment]
Might be resolved in https://github.com/SemanticMediaWiki/SemanticTasks/pull/13

**Comment by PeterTheOne** [comment]
Thanks, yes I already noticed that in #13 . And that works there already..

**Comment by PeterTheOne** [comment]
merged #13 , this should be fixed. please reopen if it still persists.
