### ISSUE TITLE
Make 2.0.0 release

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticTasks#20]
Tracking issue for the 2.0.0 release.
- [Release notes](https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/docs/RELEASE-NOTES.md)
- Changes since 1.7.0 ?

## 
- [x] Write RELEASE NOTES
- [x] Update "README.md"
- [x] Update `"/docs/"`
- [x] Update "composer.json"
- [x] Update version number "extension.json"
- [x] Create tag
- [x] Add release to [Wikidata](https://www.wikidata.org/wiki/Q21678507)
- [x] Update [homepage](https://www.mediawiki.org/wiki/Extension:Semantic_Tasks)
- [x] Announce via mail
- [x] Do a release tweet on Twitter
- [x] Run `composer update` on smw.o
- [x] Update "LocalSettings.php"
- [x] Start development of new version 
  - [x] Update "extension.json" (new alpha version)

(todo list copied from latest release of the SIL Extension)

**Comment by kghbln** [comment]
@krabina @PeterTheOne What is the status of this? Anyways found another error for MW 1.34 #24

**Comment by krabina** [comment]
The extension is now working great for MW 1.31LTS. And this is IMO the goal for a 2.0 release. Any problems related to MW > 1.31 should be put on the agenda for a 2.1 release. Let's try to make a 2.0 happen!

**Comment by kghbln** [comment]
Well, ok, once #15 is done I could do the release.

**Comment by kghbln** [comment]
@krabina I very much suspect that you would like to do the honours of sending an e-mail about this release as well as tweeting about it. :)

**Comment by kghbln** [comment]
Also now added code documenation to https://doc.semantic-mediawiki.org/modules.html
