### ISSUE TITLE
Edit API broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticTasks#30]
### Setup

- MediaWiki | 1.34.0-rc.1 (8c60cd5)19:12, 18 November 2019
- PHP | 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (9a9a3d5) 15:40, 25 November 2019
- Semantic Tasks | 2.0.0-alpha (cb85bb1) 15:15, 25 November 2019

### Issue

API error - Error at /../w/extensions/SemanticTasks/src/Assignees.php(211)

Seen here: https://sandbox.semantic-mediawiki.org/wiki/GeoJson:Berlin

Steps to reproduce: login in and add marker to map

![image](https://user-images.githubusercontent.com/146040/69605874-9e0f7600-1021-11ea-9843-a3826072f829.png)

### Backtrace
```
#0 /../w/extensions/SemanticTasks/src/Assignees.php(45): ST\Assignees->getProperties(string, WikiPage, Revision)
#1 /../w/extensions/SemanticTasks/src/Assignees.php(25): ST\Assignees->getCurrentAssignees(WikiPage, NULL)
#2 /../w/includes/Hooks.php(174): ST\Assignees->saveAssignees(WikiPage, User, Maps\MediaWiki\Content\GeoJsonContent, CommentStoreComment, integer, NULL, NULL, integer, Status)
#3 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#4 /../w/includes/Storage/PageUpdater.php(736): Hooks::run(string, array)
#5 /../w/includes/page/WikiPage.php(1931): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#6 /../w/includes/EditPage.php(2341): WikiPage->doEditContent(Maps\MediaWiki\Content\GeoJsonContent, CommentStoreComment, integer, boolean, User, string, array, integer)
#7 /../w/includes/EditPage.php(1617): EditPage->internalAttemptSave(array, boolean)
#8 /../w/includes/api/ApiEditPage.php(383): EditPage->attemptSave(array)
#9 /../w/includes/api/ApiMain.php(1598): ApiEditPage->execute()
#10 /../w/includes/api/ApiMain.php(537): ApiMain->executeAction()
#11 /../w/includes/api/ApiMain.php(508): ApiMain->executeActionWithErrorHandling()
#12 /../w/api.php(87): ApiMain->execute()
#13 {main}
```

**Comment by PeterTheOne** [comment]
I tried, but I got no error. Maybe I just don't know how to persistently add a marker.

Important info is in your screenshot, it points to https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/src/Assignees.php#L211 . I guess there needs to be a check if getExtensionData returns null.

**Comment by PeterTheOne** [comment]
#32 is merged, this should be a fix. Fix not please reopen this issue.

**Comment by JeroenDeDauw** [comment]
indeed fixed
