### ISSUE TITLE
On creation of new page, 2 emails are sent

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticTasks#38]
### Setup and configuration

- SMW version: 3.1.1
- ST version: 2.0
- MW version: 1.31
- PHP version: 7.1.26 (fpm-fcgi)
- DB (MySQL etc. and version):  MySQL | 5.5.62-cll

### Issue
When a new page is created and at the same time a task is assigned, two e-mails are send. 

Steps to reproduce the observation:
Creat a new page "Test" with the content
`[[Assigned to::User:Krabina]]`
Then User:Krabina will get 2 E-Mails

One titled "New task: Test", one with "Assigned task:Test".

Only one e-mail shoudl be sent in this case

**Comment by PeterTheOne** [comment]
From the code it looks like those might be group notifications, is your User is some group?

**Comment by krabina** [comment]
Every mediawiki user is in some groups (like "user" or "autoconfirmed"). This is an admin user, but it also happens if non-admin-users do it.

**Comment by PeterTheOne** [comment]
I mean there is some `Assigned to group` property, but maybe it is not it.

Seems like both of these are called:

- https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/src/SemanticTasksMailer.php#L105
- https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/src/SemanticTasksMailer.php#L128
