### ISSUE TITLE
Switch to extension registration and make it installable with Composer

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticTasks#4]
@PeterTheOne @krabina

I believe that is pretty much a must for the upcoming version 2.0 which is meant to be compatible with SMW 3.x

**Comment by mwjames** [comment]
> extension registration and make it installable with Composer

To minimize maintenance effort among SMW repos/extensions hosted on GitHub it is discouraged to use PHP hooks declaration and class registration in `extension.json` (see [0] as reference).

[0] https://github.com/SemanticMediaWiki/SemanticNotifications/pull/30

**Comment by mwjames** [comment]
Has been registered under https://packagist.org/packages/mediawiki/semantic-tasks

**Comment by mwjames** [comment]
README.md and `composer.json` still have a reference to Semantic MediaWiki 1.8, this is a lie and needs at least a lower bound of SMW 3.0!
