### ISSUE TITLE
Set up code coverage and code quality mechanism

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticTasks#5]
@PeterTheOne @krabina Even in a rudimentary state this is probably a very good to have mechanism

**Comment by PeterTheOne** [comment]
I'm all for that. There is already a grunt based test that works and lints the i18n files and there is a composer based linting of php code, that fails for me because the `extensions` folder somehow isn't ignored. I already tried to fix that without success.

**Comment by PeterTheOne** [comment]
I did some things in #13 but I think I need help with setting this up with travis and I had some `DBConnectionError` issue.

**Comment by mwjames** [comment]
> I did some things in #13 but I think I need help with setting this up with travis and I had some DBConnectionError issue.

Has been fixed with #16:

https://travis-ci.org/SemanticMediaWiki/SemanticTasks/jobs/573403289

```
Using PHP 7.1.27

Semantic Tasks:     2.0.0-alpha

Semantic MediaWiki: 3.1.0-alpha, git: 732a401, SMWSQLStore (mysql:5.7.25-0ubuntu0.16.04.2)
MediaWiki:          1.34.0-alpha, git: n/a, MediaWiki vendor autoloader
Site language:      en

Execution time:     2019-08-18 12:36
Debug logs:         Disabled

Xdebug:             2.7.0
Intl/ICU:           1.1.0 / 55.1

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.27 with Xdebug 2.7.0
Configuration: /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticTasks/phpunit.xml.dist

..                                                                  2 / 2 (100%)

Time: 226 ms, Memory: 26.00MB
```

**Comment by mwjames** [comment]
@kghbln @PeterTheOne Please review the changes I made in #16 so that you are able to make adjustments without my help. Furthermore, on the matter of coverage and scrutinizer-ci integration maybe @JeroenDeDauw can help and dedicate 5 min to set this up.

**Comment by PeterTheOne** [comment]
Thanks!

**Comment by PeterTheOne** [comment]
#27 and #28 added some more tests
