### ISSUE TITLE
Make "ST_CheckForReminders.php" obey generic script parameters

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticTasks#8]
### Setup and configuration

- MediaWiki | 1.32.1 (c6f078c)05:11, 11. Mai 2019
- PHP | 7.2.17-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.2
- Semantic MediaWiki | 3.1.0-alpha (81df573) 14:51, 13. Mai 2019
- SemanticTasks | 2.0.0-alpha (7f4b7e3) 09:47, 16. Mai 2019

### Issue

```bash
php ST_CheckForReminders.php -- quiet
```
still returns the "ST check for reminders" message.

I guess it will be good to move the script to the "maintenance" directory and rename it to "checkForReminders.php" at the same time. Since we are looking at a breaking release anyways ...

**Comment by kghbln** [comment]
@krabina @PeterTheOne FYI

**Comment by PeterTheOne** [comment]
resolved in https://github.com/SemanticMediaWiki/SemanticTasks/pull/12
